# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab3WB():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab3WB(self):
    self.driver.get("https://www.wildberries.ru/")
    self.driver.set_window_size(1507, 859)
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("кофе дрип")
    self.driver.find_element(By.CSS_SELECTOR, ".selected b").click()
    self.driver.execute_script("window.scrollTo(0,79)")
    self.driver.execute_script("window.scrollTo(0,194)")
    self.driver.find_element(By.CSS_SELECTOR, "#c169074255 .product-card__link").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".mo-button_view_fill:nth-child(1) > .mo-flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mo-button_view_fill:nth-child(1) > .mo-flex").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide:nth-child(6) > .slideAnchor--CwO_y")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-next > .slideAnchor--CwO_y")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
